# Generated by Django 3.0.6 on 2020-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
